import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        const orderdataList =[
            {id:'1', orderNumber: '84795045', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'2', orderNumber: '96853467', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'3', orderNumber: '34266840', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'4', orderNumber: '37866840', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'5', orderNumber: '74353467', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'6', orderNumber: '54386215', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'7', orderNumber: '13456230', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'8', orderNumber: '94523687', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'9', orderNumber: '98512349', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'10', orderNumber: '90453264', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'11', orderNumber: '18325672', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'12', orderNumber: '82345671', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'13', orderNumber: '98432653', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'14', orderNumber: '84512487', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] },
            {id:'15', orderNumber: '94746554', status: 'Click To Receive',name:'Vinod Rathod',Address:'Ameerpet, Hyderabad, Telengana, 700018', order:[{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'},{orderId:'1',orderName:'Chicken Pizza', amount:'120.34'}] }
          ]
        return {orderdataList};
      }

}